# NAME: Brendon Ng
# EMAIL: brendonn8@gmail.com
# ID: 304925492

default:
	cp lab3b.py lab3b
	chmod +x lab3b
dist:
	tar -czf lab3b-304925492.tar.gz Makefile README lab3b.py
clean:
	rm -f *~ *.tar.gz lab3b
