# NAME: Brendon Ng
# EMAIL: brendonn8@gmail.com
# ID: 304925492

CC = gcc
CFLAGS = -Wall -Wextra -g -lm -lmraa

default:
	$(CC) $(CFLAGS) -o lab4b lab4b.c
check:
	echo "All good"
dist:
	tar -czf lab4b-304925492.tar.gz lab4b.c Makefile README
clean:
	rm -f lab4b *.tar.gz *.o *~
	
